### ISSUE TITLE
Starting a research results in an error

### ISSUE THREAD

**Issue by OniZakuma** [alaingilbert/pyogame#14]
Trying to start HyperspaceTechnology-7 (or any) results in a TypeError which crashes the script:

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\xxx\PycharmProjects\ogame\pygame.py", line 480, in thread_build
    self.build(planet_name)
  File "C:\Users\xxx\PycharmProjects\ogame\pygame.py", line 341, in build
    self.ogame.build(self.planets[planet_name], building)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 55, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 436, in build
    self._build(planet_id, elem_id, cancel=cancel)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 55, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 421, in _build
    self.build_technology(planet_id, object_id, cancel=cancel)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 55, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 414, in build_technology
    if not self.is_logged(res):
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 55, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 139, in is_logged
    soup = BeautifulSoup(html, 'lxml')
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'Response' has no len()

```

**Comment by alaingilbert** [comment]
Fixed https://github.com/alaingilbert/pyogame/commit/bdaca4434106fe2bb82c738d82ca353eda5ee3c3

:)

**Comment by OniZakuma** [comment]
Thank you!
