### ISSUE TITLE
Bot is not working anymore?

### ISSUE THREAD

**Issue by agustinscaz** [alaingilbert/pyogame#40]
Today using the bot I try send_fleet() method, and is not working.

Can you fix it please?

Thanks!

**Comment by alaingilbert** [comment]
I just tried it, and it works fine.

My test code looks like this:
```py
bot = OGame(UNIVERSE, USERNAME, PASSWORD)
ids = bot.get_planet_ids()
ships = [(Ships['SmallCargo'], 1)]
speed = Speed['100%']
where = {'galaxy': 4, 'system': 208, 'position': 8}
mission = Missions['Transport']
resources = {'metal': 1, 'crystal': 2, 'deuterium': 3}
fleetID = bot.send_fleet(ids[0], ships, speed, where, mission, resources)
print("Fleet id:", fleetID)
```

**Comment by agustinscaz** [comment]
Hi @alaingilbert,

I'm testing the code but is not working (fleetId is set to None). Any solution? How can I send you logs?

Thanks in advance!

**Comment by alaingilbert** [comment]
Are you on discord ?
Feel free to add me, it'll be easier to communicate
```
agilbert
#2967
```

**Comment by Xiakit** [comment]
Hello i am trying to do the following:
`ogame = OGame('Zibal', USER, PASW, domain="de.ogame.gameforge.com")`

But i get a strange error, am i doing something wrong?

`Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    ogame = OGame('Zibal', USER, PASW, domain="de.ogame.gameforge.com")
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 56, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 39, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 119, in __init__
    self.login()
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 56, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 39, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 125, in login
    self.server_url = self.get_universe_url(self.universe)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 56, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 39, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 619, in get_universe_url
    servers = self.get_servers(self.domain)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 56, in wrapper
    res = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 39, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "C:\Python27\lib\site-packages\ogame\__init__.py", line 611, in get_servers
    for opt in select.findAll('option'):
AttributeError: 'NoneType' object has no attribute 'findAll'`

Thank you :)

**Comment by PiecePaperCode** [comment]
obsolet
