### ISSUE TITLE
ImportError: cannot import name 'Ogame'

### ISSUE THREAD

**Issue by PiecePaperCode** [alaingilbert/pyogame#45]
I always get an error.
here is my code
`from ogame import Ogame`
`empire = Ogame('world','user','pw')`
`print(empire.is_under_attack())`
`>>>ImportError: cannot import name 'Ogame'`

**Comment by alaingilbert** [comment]
```py
from ogame import OGame
```
From the readme

**Comment by PiecePaperCode** [comment]
`from` ogame import `Ogame`
._.

**Comment by PiecePaperCode** [comment]
pydev debugger: starting

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 111, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\debugger.py", line 36, in debug
    run(address, filename, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 47, in run_file
    run(argv, addr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 98, in _run
    _pydevd.main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1628, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1035, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\--\source\repos\Ogame\Ogame\Ogame.py", line 2, in <module>
    from ogame import Ogame
ImportError: cannot import name 'Ogame'

**Comment by alaingilbert** [comment]
`Ogame` does not exists... Fix your typo, it's `OGame` (case sensitive)

**Comment by PiecePaperCode** [comment]
FIxed it mb
