### ISSUE TITLE
Build not woking

### ISSUE THREAD

**Issue by LAntoine** [alaingilbert/pyogame#6]
when I try to build something I get the following error : 

```
Traceback (most recent call last):
  File "/home/lantoine/python-workspace/script_ogame.py", line 6, in <module>
    ogame.build(PLANET_ID, Buildings['MetalMine'])
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 55, in wrapper
    res = fn(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 466, in build
    self._build(planet_id, elem_id)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 55, in wrapper
    res = fn(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 449, in _build
    self.build_building(planet_id, object_id)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 55, in wrapper
    res = fn(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/ogame/__init__.py", line 427, in build_building
    token = form.find('input', {'name': 'token'}).get('value')
AttributeError: 'NoneType' object has no attribute 'find'
```

I used this command :

```
PLANET_ID = ogame.get_planet_ids()
ogame.build(PLANET_ID, Buildings['MetalMine'])
```

**Comment by alaingilbert** [comment]
```
ogame.get_planet_ids()
```

Returns an array of ids... like : `[1, 2, 3]`

So your code is invalid.
You could do something  like this instead:

```
PLANET_ID = ogame.get_planet_ids()[0]
```

**Comment by LAntoine** [comment]
Thanks !

**Comment by alaingilbert** [comment]
:) let me know if you have any other issues !
